config/routes.rb
Rails.application.routes.draw do
  resources :websites
  root 'websites#index'

end

app/models/page_content.rb
class PageContent < ActiveRecord::Base

  belongs_to :web_page

end

app/models/web_page.rb
class WebPage < ActiveRecord::Base

  belongs_to :website
  has_many :page_contents

  accepts_nested_attributes_for :page_contents, :allow_destroy => true

end

app/models/website.rb
class Website < ActiveRecord::Base

  has_many :web_pages

  accepts_nested_attributes_for :web_pages, :allow_destroy => true

  attr_accessor :next_page_link_path, :pagination_links_parent_path, :pagination_links_path, :products_parent_path, :products_link_path, :file_name, :sheet_name, :product_links, :agent, :page, :web_page

  def parse_products
    web_pages.each do |web_page|
      @web_page = web_page
      set_params
      parse_webpage
    end
  end

  def parse_webpage
    get_all_product_links
    sheet, book = return_worksheet_and_workbook
    @product_links.each_with_index do |product_link, product_index|
      agent = Mechanize.new
      link = "http://www.episcopalacademy.org/fs/elements/1741?is_draft=false&show_profile=true&const_id=#{product_link}"
      page = agent.get(link)
      sleep(1)
      page_contents_data = @web_page.page_contents
      page_contents_length = page_contents_data.length
      page_contents_data.each_with_index do |page_content, column_index|
        if product_index == 0
          cell = sheet.add_cell(0, column_index, page_content.content_field)
        end
        if page_content.content_field == 'School Email'
          email_params = page.at(page_content.content_path)
          if email_params.present?
            email_params = email_params.text.strip.split('insertEmail(')[1..-1].join(',').split(');')[0..-2][0].gsub(/"/, '').split(',')
          end
          content = Website.generate_email(email_params)
        else
          content = page.at(page_content.content_path)
          content = content.text if content.present?
        end
        if content.present?
          cell = sheet.add_cell(product_index+1, column_index, content.strip)
        end
      end
    end
    book.write @file_name
  end

  private

    def set_params
      webpage_url = @web_page.url
      @next_page_link_path = @web_page.next_page_link_path
      @pagination_links_parent_path = @web_page.pagination_links_parent_path
      @pagination_links_path = @web_page.pagination_links_path
      @products_parent_path = @web_page.products_parent_path
      @products_link_path = @web_page.products_link_path
      @file_name = @web_page.file_name
      @sheet_name = @web_page.sheet_name
      @product_links = []
      @agent = Mechanize.new
      @page = @agent.get(webpage_url)
    end

    def self.generate_email(email_params)
      email = ''
      if email_params.present?
        t = email_params[0].strip
        n = email_params[1].strip
        r = email_params[2].strip
        i = email_params[3].strip
        email = r.split("").reverse().join("")+"@"+n.split("").reverse().join("")
      end
      email
    end

    def return_workbook
      if File.exist?(@file_name)
        book = RubyXL::Parser.parse(@file_name)
      else
        book = RubyXL::Workbook.new
      end
      return book
    end

    def return_worksheet_and_workbook
      book = return_workbook
      sheet = book[@sheet_name]
      if sheet.blank?
        @sheet_name = @sheet_name.gsub("/", "-")
        sheet = book[@sheet_name]
        if sheet.blank?
          sheet = book["Sheet1"]
          if sheet.present?
            sheet.sheet_name = @sheet_name
          else
            sheet = book.add_worksheet(sheet_name)
          end
        end
      end
      sheet.delete_column
      return [sheet, book]
    end

    def get_product_view_links
      @page.search(products_parent_path).each do |product| 
        constituent_id = product.at(products_link_path).attr('data-constituent-id').strip
        @product_links << constituent_id
      end
    end

    def get_all_product_links
      if @page.present?
        next_page = @page.at(@next_page_link_path)
        pagination_links = @pagination_links_parent_path.present? ? @page.search(@pagination_links_parent_path) : nil
        get_product_view_links
        if next_page.present?
          while next_page.present? do
            next_page_link = next_page.attr('href')
            @page = @agent.get(next_page_link)
            sleep(1)
            next_page = @page.at(@next_page_link_path)
            get_product_view_links
          end
        elsif pagination_links.present?
          pagination_links = pagination_links[1..-1]
          pagination_links.each do |pagination_link|
            pagination_link = pagination_link.attr('href')
            @page = @agent.get(pagination_link)
            sleep(1)
            get_product_view_links
          end
        end
      else
        puts "page doesn't exist"
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  def index
    @websites = Website.all
  end

  def show
  end

  def new
    @website = Website.new
    build_objects
  end

  def edit
  end

  def create
    @website = Website.new(website_params)
    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
    end
  end

  private

    def set_website
      @website = Website.find(params[:id])
    end

    def build_objects
      web_page = @website.web_pages.build
      web_page.page_contents.build
    end

    def website_params
      params.require(:website).permit(
        :name,
        :_destroy,
        web_pages_attributes: [
          :id,
          :_destroy,
          :url,
          :next_page_link_path,
          :pagination_links_parent_path,
          :pagination_links_path,
          :products_parent_path,
          :products_link_path,
          :website_id,
          :file_name,
          :sheet_name,
          page_contents_attributes: [
            :id,
            :_destroy,
            :content_path,
            :content_field,
            :web_page_id
          ]
        ]
      )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type.to_sym
    when :success
      "alert-success"
    when :error
      "alert-error"
    when :alert
      "alert-block"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_nested_fields(this)")
  end

  def link_to_add_fields(name, f, association, cssClass, title)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
     end
    link_to name, "#", :onclick => h("add_nested_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"), class: cssClass, title: title, remote: true
  end

  def link_to_function(name, *args, &block)
    html_options = args.extract_options!.symbolize_keys
    function = block_given? ? update_page(&block) : args[0] || ''
    onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
    href = html_options[:href] || '#'
    content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end

end

app/views/layouts/_error_messages.html.haml
- if object.errors.any?
  .alert.alert-error
    %a.close{"data-dismiss" => "alert"} ×
    %ul
      - object.errors.full_messages.each do |msg|
        = content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String)

app/views/layouts/_flash_messages.html.haml
- flash.each do |type, message|
  %div{class: "alert #{bootstrap_class_for(type)} fade in"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ParseAmazon
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .row
      = render :partial => "layouts/flash_messages"
      = yield

app/views/websites/_form.html.haml
.panel.panel-default
  .panel-heading
    .panel-title
      .row
        .col-md-4
          Add website details
        .col-md-8
          .pull-right
            = link_to "Back", "/websites", class: "btn btn-info active"
  .panel-body
    = form_for(@website, :html => { :role => 'form' }) do |f|
      = render 'layouts/error_messages', { object: @website }
      .form-group.row
        .col-md-2
          = f.label :name, 'Website Name'
        .col-md-10
          = f.text_field :name, autofocus: true, size: 25

      = f.fields_for :web_pages do |builder|
        = render 'web_page_fields', :f => builder
      = link_to_add_fields "Add Web Page", f, :web_pages, "btn btn-default", "Add a new Web Page"
      .actions.text-center
        = f.submit "Submit", :class => "btn btn-success"

app/views/websites/_page_content_fields.html.haml
.fields.container
  .gray-border
    .form-group.row
      .col-md-2
        = f.label :content_field
      .col-md-10
        = f.text_field :content_field, autofocus: true, size: 100
    .form-group.row
      .col-md-2
        = f.label :content_path
      .col-md-10
        = f.text_field :content_path, autofocus: true, size: 100
    = link_to_remove_fields "Remove Page Content Fields", f

app/views/websites/_web_page_fields.html.haml
.fields.container.gray-border
  .form-group.row
    .col-md-2
      = f.label :url, "Web page url"
    .col-md-10
      = f.text_field :url, autofocus: true, size: 100
  .form-group.row
    .col-md-2
      = f.label :next_page_link_path
    .col-md-10
      = f.text_field :next_page_link_path, autofocus: true, size: 100
  .form-group.row
    .col-md-2
      = f.label :pagination_links_parent_path
    .col-md-10
      = f.text_field :pagination_links_parent_path, autofocus: true, size: 100
  .form-group.row
    .col-md-2
      = f.label :pagination_links_path
    .col-md-10
      = f.text_field :pagination_links_path, autofocus: true, size: 100
  .form-group.row
    .col-md-2
      = f.label :products_parent_path
    .col-md-10
      = f.text_field :products_parent_path, autofocus: true, size: 100
  .form-group.row
    .col-md-2
      = f.label :products_link_path
    .col-md-10
      = f.text_field :products_link_path, autofocus: true, size: 100
  .form-group.row
    .col-md-2
      = f.label :file_name
    .col-md-10
      = f.text_field :file_name, autofocus: true, size: 100
  .form-group.row
    .col-md-2
      = f.label :sheet_name
    .col-md-10
      = f.text_field :sheet_name, autofocus: true, size: 100

  = link_to_remove_fields "Remove Webpage Fields", f

  = f.fields_for :page_contents do |builder|
    = render 'page_content_fields', :f => builder
  .row
    = link_to_add_fields "Add a page content", f, :page_contents, "btn btn-default", "Add a new page content"

app/views/websites/edit.html.haml
%h1 Editing Website
= render 'form'
= link_to 'Show', @website
|
= link_to 'Back', websites_path

app/views/websites/index.html.haml
%h1 Listing Websites
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @websites.each do |website|
      %tr
        %td= website.name
        %td= link_to 'Show', website
        %td= link_to 'Edit', edit_website_path(website)
        %td= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to 'New Website', new_website_path

app/views/websites/new.html.haml
%h1 New Website

= render 'form'

= link_to 'Back', websites_path

app/views/websites/show.html.haml
%p
  %strong Name:
  = @website.name

= link_to 'Edit', edit_website_path(@website)
|
= link_to 'Back', websites_path